import turtle
turtle.pensize(3)
turtle.goto(0, 0)
turtle.pencolor('blue')
turtle.circle(25)
turtle.penup()
turtle.goto(20, -20)
turtle.pendown()
turtle.pencolor('yellow')
turtle.circle(25)
turtle.penup()
turtle.goto(40, 0)
turtle.pendown()
turtle.pencolor('black')
turtle.circle(25)
turtle.penup()
turtle.goto(60, -20)
turtle.pendown()
turtle.pencolor('green')
turtle.circle(25)
turtle.penup()
turtle.goto(80, 0)
turtle.pendown()
turtle.pencolor('red')
turtle.circle(25)



