import turtle
turtle.hideturtle()
turtle.Screen().bgcolor("DarkBlue")
turtle.up()
turtle.goto(0, - 150)
turtle.down()
turtle.fillcolor("Gold")
turtle.pencolor("Gold")
turtle.begin_fill()
turtle.circle(150)
turtle.end_fill()

turtle.up()
turtle.goto(50, -150)
turtle.down()
turtle.pencolor("DarkBlue")
turtle.fillcolor("DarkBlue")
turtle.begin_fill()
turtle.circle(150)
turtle.end_fill()